### ISSUE TITLE
Unown language won't stop

### ISSUE THREAD

**Issue by Lyfira** [SheerSt/pokewilds#114] opened 2022-08-04 10:05 UTC
I just started plying today and collected some unown items and read some signs but now whenever I fight or collect something, interact with a Pokémon that could attack me if I interact again, every message is in the unown language and idk how to turn that off ( if that's possible ).
It doesn't happen with the menu or bag ( items ), Pokémon list etc.

**Comment by Lyfira** [comment] 2022-08-04 11:09
> I just started plying today and collected some unown items and read some signs but now whenever I fight or collect something, interact with a Pokémon that could attack me if I interact again, every message is in the unown language and idk how to turn that off ( if that's possible ).
> It doesn't happen with the menu or bag ( items ), Pokémon list etc.

I just changed areas and it's back to normal. I still dk if that was supposed to happen.

**Comment by link27017** [comment] 2022-08-04 17:33
It may be because of what happens with the Unown

I explain when you read a sign it can happen that some strange lyrics come out and the music is changed this is because if it passes through tall grass an Unown will appear after confronting the music and the strange lyrics will be removed

**Comment by fourlastor** [comment] 2022-10-17 12:15
@link27017 that's correct :) closing as this is working as intended

**Closed as completed by fourlastor** 2022-10-17 12:15 UTC
