### ISSUE TITLE
Level-up moves

### ISSUE THREAD

**Issue by Ryvinky** [SheerSt/pokewilds#136] opened 2022-08-14 06:36 UTC
Often when reaching the level they should learn a move (according to documents posted here), pokemon will not learn the move. Several pokemon in my team became useless as they leveled up because they never learned stronger moves

**Comment by Timoris** [comment] 2022-08-15 20:37
Duplicate of https://github.com/SheerSt/pokewilds/issues/121

**Comment by fourlastor** [comment] 2022-09-13 17:28
Hi, this is because we still didn't implement all the moves, we're working on it :)

**Closed as completed by fourlastor** 2022-09-13 17:28 UTC

**Comment by Codz155** [comment] 2022-11-13 01:26
@fourlastor pokemon don't learn Some Moves that already in the game like quick Attack on eevee at lvl 10 its supposed learn it but it does not . At lease for me

**Comment by fourlastor** [comment] 2022-11-16 11:14
@Codz155 eevee learnset (the one present in the released game) follows the [generation 2 learnset](https://pokemondb.net/pokedex/eevee/moves/2)
