### ISSUE TITLE
No .exe

### ISSUE THREAD

**Issue by BrogoWasTaken** [SheerSt/pokewilds#299] opened 2022-11-13 21:42 UTC
So I was downloding the Windows 64 file and couldn't see the .exe that I had to open.
Someone please help me.

**Comment by BrogoWasTaken** [comment] 2022-11-13 21:47
Hello?

**Comment by MindeKing** [comment] 2022-11-15 05:01
If I remember correctly, by default, Windows hides file extensions from the user (.jpg, .png, .exe, etc.)
If you extracted the zip and your folder looks something like this,
![image](https://user-images.githubusercontent.com/26449194/201829706-2a3c7fbd-b577-44f3-af21-e0472ed826b9.png)
then Windows is hiding your file extensions.

To solve this, simply click the chevron in the upper right-hand corner of the window.
![image](https://user-images.githubusercontent.com/26449194/201829872-19b97927-bc0f-4b58-91cd-39a4473e8dde.png)

Click the tab that says "View" in the upper _left_-hand corner of the window,
![image](https://user-images.githubusercontent.com/26449194/201829976-62c378dd-9ab8-4888-a8fa-dfdd887f233e.png)

And check the box that says "File name extensions"
![image](https://user-images.githubusercontent.com/26449194/201830054-2b66a76b-2e4d-4507-8539-699e80f2b8c1.png)

Your folder should hopefully look something like this:
![image](https://user-images.githubusercontent.com/26449194/201830129-e1897ea9-8128-4c1a-9dab-e9ce1bf1b2b5.png)

Hopefully I've accurately diagnosed the cause of your problem, and, if not, please be sure to add more context to issues and bug reports in the future (this also works well as general life advice).

**Comment by fourlastor** [comment] 2023-01-02 13:14
Closing as this seems to be resolved

**Closed as completed by fourlastor** 2023-01-02 13:14 UTC
